services:
  n8n:
    build:
      context: .
      dockerfile: CustomDockerfile
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_PATH=/
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_LOG_LEVEL=debug
      - DEBUG=true
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_METRICS=true
    depends_on:
      - postgres
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  n8n_data:
  postgres_data:
